import  Header  from "../components/Header/Header";
import  Footer  from "../components/Footer/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute:'',
    default: 'NextJS Tutorial',
    template: '%s | Martin\'s Test page'
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
